// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMQ1m3YkVyFTG6rMtot7hs80udRP0T4Yc',
    appId: '1:335557129340:web:452c3d593b9e546a4d85f9',
    messagingSenderId: '335557129340',
    projectId: 'mynewapp25-de508',
    authDomain: 'mynewapp25-de508.firebaseapp.com',
    storageBucket: 'mynewapp25-de508.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW2R2ATNnodTQa1fco4f7TfduXV5w561Q',
    appId: '1:335557129340:android:be07e2c09705b4bd4d85f9',
    messagingSenderId: '335557129340',
    projectId: 'mynewapp25-de508',
    storageBucket: 'mynewapp25-de508.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB09FN8IHxTdGQC8uONHn_NYthsC1B9_78',
    appId: '1:335557129340:ios:f50a6792a6433db84d85f9',
    messagingSenderId: '335557129340',
    projectId: 'mynewapp25-de508',
    storageBucket: 'mynewapp25-de508.firebasestorage.app',
    androidClientId: '335557129340-f4cg97lu5n13sf3oge3b60rdbl8d40sd.apps.googleusercontent.com',
    iosClientId: '335557129340-5kp92ciu7r8n83cnm5k0t752b0brkfqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB09FN8IHxTdGQC8uONHn_NYthsC1B9_78',
    appId: '1:335557129340:ios:f50a6792a6433db84d85f9',
    messagingSenderId: '335557129340',
    projectId: 'mynewapp25-de508',
    storageBucket: 'mynewapp25-de508.firebasestorage.app',
    androidClientId: '335557129340-f4cg97lu5n13sf3oge3b60rdbl8d40sd.apps.googleusercontent.com',
    iosClientId: '335557129340-5kp92ciu7r8n83cnm5k0t752b0brkfqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMQ1m3YkVyFTG6rMtot7hs80udRP0T4Yc',
    appId: '1:335557129340:web:1f831dbf550670b04d85f9',
    messagingSenderId: '335557129340',
    projectId: 'mynewapp25-de508',
    authDomain: 'mynewapp25-de508.firebaseapp.com',
    storageBucket: 'mynewapp25-de508.firebasestorage.app',
  );
}
